package AsyCry.UI;

import javax.swing.JFrame;

/**
 * Classe destinada ao front-end da aplicação.
 * @author chris
 */
public class AppUI extends JFrame {

    /**
     * Cria nova janela.
     */
    public AppUI() {
        initComponents();
    }
    
    /**
     * Executa a aplicação.
     */
    public void run() {
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserInputFile = new javax.swing.JFileChooser();
        jFileChooserOutputFile = new javax.swing.JFileChooser();
        jFileChooserOpenKey = new javax.swing.JFileChooser();
        jFileChooserSaveKey = new javax.swing.JFileChooser();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelCrypto = new javax.swing.JPanel();
        jLabelInput1 = new javax.swing.JLabel();
        jLabelOutput1 = new javax.swing.JLabel();
        jLabelKey1 = new javax.swing.JLabel();
        jTextFieldInputFile1 = new javax.swing.JTextField();
        jTextFieldOutputFile1 = new javax.swing.JTextField();
        jTextFieldKey1 = new javax.swing.JTextField();
        jButtonOpenFile1 = new javax.swing.JButton();
        jButtonSaveFile1 = new javax.swing.JButton();
        jButtonOpenKey1 = new javax.swing.JButton();
        jButtonCrypto = new javax.swing.JButton();
        jPanelDecrypto = new javax.swing.JPanel();
        jLabelInput2 = new javax.swing.JLabel();
        jLabelOutput2 = new javax.swing.JLabel();
        jLabelKey2 = new javax.swing.JLabel();
        jTextFieldInputFile2 = new javax.swing.JTextField();
        jTextFieldOutputFile2 = new javax.swing.JTextField();
        jTextFieldKey2 = new javax.swing.JTextField();
        jButtonOpenFile2 = new javax.swing.JButton();
        jButtonSaveFile2 = new javax.swing.JButton();
        jButtonOpenKey2 = new javax.swing.JButton();
        jButtonDecrypto = new javax.swing.JButton();
        jPanelKeys = new javax.swing.JPanel();
        jLabelPublicKey = new javax.swing.JLabel();
        jLabelPrivateKey = new javax.swing.JLabel();
        jTextFieldPublicKey = new javax.swing.JTextField();
        jTextFieldPrivateKey = new javax.swing.JTextField();
        jButtonSaveKey1 = new javax.swing.JButton();
        jButtonSaveKey2 = new javax.swing.JButton();
        jButtonGenerate = new javax.swing.JButton();
        jPanelConsole = new javax.swing.JPanel();
        jScrollPaneConsole = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();

        jFileChooserInputFile.setCurrentDirectory(null);
        jFileChooserInputFile.setDialogTitle("Abrir arquivo");

        jFileChooserOutputFile.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooserOutputFile.setCurrentDirectory(null);
        jFileChooserOutputFile.setDialogTitle("Salvar arquivo");

        jFileChooserOpenKey.setCurrentDirectory(null);
        jFileChooserOpenKey.setDialogTitle("Abrir chave");

        jFileChooserSaveKey.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooserSaveKey.setCurrentDirectory(null);
        jFileChooserSaveKey.setDialogTitle("Salvar chave");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criptografia Assimétrica");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setName("appFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 480));

        jTabbedPane.setFocusable(false);

        jPanelCrypto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCrypto.setFocusable(false);

        jLabelInput1.setText("Entrada");

        jLabelOutput1.setText("Saída");

        jLabelKey1.setText("Chave");
        jLabelKey1.setPreferredSize(new java.awt.Dimension(33, 22));

        jButtonOpenFile1.setText("...");

        jButtonSaveFile1.setText("...");

        jButtonOpenKey1.setText("...");

        jButtonCrypto.setText("CRIPTOGRAFAR");

        javax.swing.GroupLayout jPanelCryptoLayout = new javax.swing.GroupLayout(jPanelCrypto);
        jPanelCrypto.setLayout(jPanelCryptoLayout);
        jPanelCryptoLayout.setHorizontalGroup(
            jPanelCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCryptoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInput1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabelOutput1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKey1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldOutputFile1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jTextFieldInputFile1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jTextFieldKey1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOpenFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanelCryptoLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jButtonCrypto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(194, 194, 194))
        );
        jPanelCryptoLayout.setVerticalGroup(
            jPanelCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCryptoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInputFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenFile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOutputFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveFile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenKey1))
                .addGap(18, 18, 18)
                .addComponent(jButtonCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Criptografar", jPanelCrypto);

        jPanelDecrypto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelDecrypto.setFocusable(false);

        jLabelInput2.setText("Entrada");

        jLabelOutput2.setText("Saída");

        jLabelKey2.setText("Chave");
        jLabelKey2.setPreferredSize(new java.awt.Dimension(33, 22));

        jButtonOpenFile2.setText("...");

        jButtonSaveFile2.setText("...");

        jButtonOpenKey2.setText("...");

        jButtonDecrypto.setText("DECRIPTOGRAFAR");

        javax.swing.GroupLayout jPanelDecryptoLayout = new javax.swing.GroupLayout(jPanelDecrypto);
        jPanelDecrypto.setLayout(jPanelDecryptoLayout);
        jPanelDecryptoLayout.setHorizontalGroup(
            jPanelDecryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDecryptoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDecryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInput2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabelOutput2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKey2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDecryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldOutputFile2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jTextFieldInputFile2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jTextFieldKey2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDecryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOpenFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanelDecryptoLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jButtonDecrypto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(194, 194, 194))
        );
        jPanelDecryptoLayout.setVerticalGroup(
            jPanelDecryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDecryptoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelDecryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInputFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenFile2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDecryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOutputFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveFile2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDecryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenKey2))
                .addGap(18, 18, 18)
                .addComponent(jButtonDecrypto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Decriptografar", jPanelDecrypto);

        jPanelKeys.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelKeys.setFocusable(false);

        jLabelPublicKey.setText("Chave Pública");

        jLabelPrivateKey.setText("Chave Privada");

        jButtonSaveKey1.setText("...");

        jButtonSaveKey2.setText("...");

        jButtonGenerate.setText("GERAR CHAVES");

        javax.swing.GroupLayout jPanelKeysLayout = new javax.swing.GroupLayout(jPanelKeys);
        jPanelKeys.setLayout(jPanelKeysLayout);
        jPanelKeysLayout.setHorizontalGroup(
            jPanelKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKeysLayout.createSequentialGroup()
                        .addComponent(jLabelPrivateKey, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrivateKey))
                    .addGroup(jPanelKeysLayout.createSequentialGroup()
                        .addComponent(jLabelPublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPublicKey)))
                .addGap(6, 6, 6)
                .addGroup(jPanelKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSaveKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveKey2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanelKeysLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jButtonGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(181, 181, 181))
        );
        jPanelKeysLayout.setVerticalGroup(
            jPanelKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeysLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveKey1))
                .addGap(26, 26, 26)
                .addGroup(jPanelKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrivateKey, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrivateKey, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveKey2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane.addTab("Gerar Chaves", jPanelKeys);

        jPanelConsole.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LOG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jScrollPaneConsole.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPaneConsole.setBorder(null);

        jTextAreaConsole.setEditable(false);
        jTextAreaConsole.setBackground(new java.awt.Color(241, 241, 241));
        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jScrollPaneConsole.setViewportView(jTextAreaConsole);

        javax.swing.GroupLayout jPanelConsoleLayout = new javax.swing.GroupLayout(jPanelConsole);
        jPanelConsole.setLayout(jPanelConsoleLayout);
        jPanelConsoleLayout.setHorizontalGroup(
            jPanelConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneConsole)
        );
        jPanelConsoleLayout.setVerticalGroup(
            jPanelConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane)
                    .addComponent(jPanelConsole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelConsole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("tabForm");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrypto;
    private javax.swing.JButton jButtonDecrypto;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JButton jButtonOpenFile1;
    private javax.swing.JButton jButtonOpenFile2;
    private javax.swing.JButton jButtonOpenKey1;
    private javax.swing.JButton jButtonOpenKey2;
    private javax.swing.JButton jButtonSaveFile1;
    private javax.swing.JButton jButtonSaveFile2;
    private javax.swing.JButton jButtonSaveKey1;
    private javax.swing.JButton jButtonSaveKey2;
    private javax.swing.JFileChooser jFileChooserInputFile;
    private javax.swing.JFileChooser jFileChooserOpenKey;
    private javax.swing.JFileChooser jFileChooserOutputFile;
    private javax.swing.JFileChooser jFileChooserSaveKey;
    private javax.swing.JLabel jLabelInput1;
    private javax.swing.JLabel jLabelInput2;
    private javax.swing.JLabel jLabelKey1;
    private javax.swing.JLabel jLabelKey2;
    private javax.swing.JLabel jLabelOutput1;
    private javax.swing.JLabel jLabelOutput2;
    private javax.swing.JLabel jLabelPrivateKey;
    private javax.swing.JLabel jLabelPublicKey;
    private javax.swing.JPanel jPanelConsole;
    private javax.swing.JPanel jPanelCrypto;
    private javax.swing.JPanel jPanelDecrypto;
    private javax.swing.JPanel jPanelKeys;
    private javax.swing.JScrollPane jScrollPaneConsole;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaConsole;
    private javax.swing.JTextField jTextFieldInputFile1;
    private javax.swing.JTextField jTextFieldInputFile2;
    private javax.swing.JTextField jTextFieldKey1;
    private javax.swing.JTextField jTextFieldKey2;
    private javax.swing.JTextField jTextFieldOutputFile1;
    private javax.swing.JTextField jTextFieldOutputFile2;
    private javax.swing.JTextField jTextFieldPrivateKey;
    private javax.swing.JTextField jTextFieldPublicKey;
    // End of variables declaration//GEN-END:variables
}
